---
# Based on https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31
name: Install pnpm
description: Setup pnpm and install dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@b9e1dbc72ff7358f971cc0b7c62c7a0d83f1068b
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .node-version
        package-manager-cache: false

    - id: cache-config
      name: Configure cache
      run: |
        pnpm_store_path="$(pnpm store path --silent)"
        if [ -z "pnpm_store_path" ]; then
          echo "Failed to get pnpm store path"
          exit 1
        fi
        mkdir -p "pnpm_store_path" || exit 1
        echo "path=$pnpm_store_path" >> $GITHUB_OUTPUT
        year_month=$(date -u '+%Y%m')
        base_key="${{ runner.os }}-pnpm-cache-v${year_month}"
        echo "key=${base_key}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
        echo "restore-keys=${base_key}-" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - id: cache-pnpm
      name: Setup pnpm cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ steps.cache-config.outputs.key }}
        path: ${{ steps.cache-config.outputs.path }}
        restore-keys: ${{ steps.cache-config.outputs.restore-keys }}

    - id: cache-development
      name: Restore development related caches
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ runner.os }}-development-cache-${{ hashFiles('**/pnpm-lock.yaml', 'package.json', 'packages/*/src/**/*.ts', 'tsconfig.json', 'eslint.config.ts', '.github/actions/pnpm-install/action.yaml') }}
        path: |
          **/.tsup
          ./docs/.astro
          **/tsconfig.tsbuildinfo
          .type-coverage
        restore-keys: ${{ runner.os }}-development-cache-

    - id: cache-eslint
      name: Restore ESLint cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        key: ${{ runner.os }}-eslint-cache-${{ hashFiles('eslint.config.ts', 'packages/eslint-config/src/**/*.ts', 'packages/*/src/**/*.ts') }}
        path: .eslintcache
        restore-keys: ${{ runner.os }}-eslint-cache-

    - name: Install dependencies
      env:
        HUSKY: '0'
      run: pnpm install ${{ steps.cache-pnpm.outputs.cache-hit == 'true' && '--prefer-offline' || '' }}
      shell: 'bash -Eeuo pipefail {0}'
