---
# Based on https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31
name: Install pnpm
description: Setup pnpm and install dependencies

runs:
  using: 'composite'
  steps:
    - id: pnpm-config
      name: Expose pnpm config(s) through "$GITHUB_OUTPUT"
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - id: cache-rotation
      name: Cache rotation keys
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - name: Setup pnpm cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    - name: Bootstrap monorepo
      env:
        HUSKY: '0'
      run: |
        # Use the bootstrap script to install dependencies and build packages
        pnpm bootstrap
      shell: 'bash -Eeuo pipefail {0}'
