---
# Based on https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31
name: Install pnpm
description: Setup pnpm and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@ac5bf11548bf5e19b8aadb8182072616590fa4a6
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: '.node-version'

    - id: cache-config
      name: Configure cache
      run: |
        pnpm_store_path=("$(pnpm config get store-dir --silent)")
        pnpm_store_path+=("$(pnpm store path --silent)")
        if [ -z "pnpm_store_path" ]; then
          echo "Failed to get pnpm store path"
          exit 1
        fi
        for pnpm_store_path in "${pnpm_store_path[@]}"; do
          mkdir -p "$pnpm_store_path" || exit 1
        done
        echo "path=$pnpm_store_path" >> $GITHUB_OUTPUT
        year_month=$(date -u '+%Y%m')
        base_key="${{ runner.os }}-pnpm-cache-v${year_month}-"
        echo "key=${base_key}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
        echo "restore-keys=${base_key}" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - name: Setup pnpm cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        key: ${{ steps.cache-config.outputs.key }}
        path: ${{ steps.cache-config.outputs.path }}
        restore-keys: ${{ steps.cache-config.outputs.restore-keys }}

    - name: Bootstrap monorepo
      env:
        HUSKY: '0'
      run: |
        # Use the bootstrap script to install dependencies and build packages
        pnpm bootstrap
      shell: 'bash -Eeuo pipefail {0}'
