packages:
  - .
  - docs
  - packages/*
  - scripts

autoInstallPeers: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  handlebars@>=4.0.0 <4.7.9: ^4.7.9
  lodash: ^4.17.23
  picomatch@>=2.3.1 <2.3.2: ^2.3.2
  picomatch@>=4.0.3 <4.0.4: ^4.0.4
  read-pkg-up@^11: npm:read-package-up
  undici@<6.24.0: ^6.24.0
  undici@>=7.17.0 <7.24.0: ^7.24.0

packageExtensions:
  eslint-plugin-jsx-a11y:
    peerDependencies:
      eslint: ^3 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9 || ^10
  eslint-plugin-react-hooks:
    peerDependencies:
      eslint: ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0 || ^9.0.0 || ^10.0.0

peerDependencyRules:
  allowedVersions:
    '@eslint-react/ast>typescript': ^6.0.0
    '@eslint-react/core>typescript': ^6.0.0
    '@eslint-react/eslint-plugin>typescript': ^6.0.0
    '@eslint-react/shared>typescript': ^6.0.0
    '@eslint-react/var>typescript': ^6.0.0
    eslint-plugin-jsx-a11y>eslint: ^10.0.0
    eslint-plugin-react-dom>typescript: ^6.0.0
    eslint-plugin-react-hooks-extra>typescript: ^6.0.0
    eslint-plugin-react-naming-convention>typescript: ^6.0.0
    eslint-plugin-react-hooks>eslint: ^10.0.0
    eslint-plugin-react-rsc>typescript: ^6.0.0
    eslint-plugin-react-web-api>typescript: ^6.0.0
    eslint-plugin-react-x>typescript: ^6.0.0
    type-coverage-core>typescript: ^6.0.0
    tsconfck>typescript: ^6.0.0
    '@astrojs/check>typescript': ^6.0.0

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
