onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
packages:
  - .
  - docs
  - 'packages/*'

autoInstallPeers: false
savePrefix: ''
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: true

overrides:
  jiti: <2.2.0
  read-pkg-up@^11: npm:read-package-up
  zod: <4.0.0
