packages:
  - .
  - docs
  - packages/*
  - scripts

autoInstallPeers: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  eslint: ^9.38.0
  read-pkg-up@^11: npm:read-package-up

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
