onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
packages:
  - .
  - docs
  - 'packages/*'

autoInstallPeers: false
savePrefix: ''
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: true
catalog:
  '@astrojs/starlight': ^0.34.4
  '@changesets/cli': 2.29.5
  '@clack/prompts': 0.11.0
  '@eslint-community/eslint-plugin-eslint-comments': 4.5.0
  '@eslint/config-inspector': 1.1.0
  '@eslint/js': 9.31.0
  '@eslint/markdown': 7.0.0
  '@manypkg/cli': 0.24.0
  '@microsoft/api-extractor': 7.52.8
  '@svitejs/changesets-changelog-github-compact': 1.2.0
  '@sxzz/create': 0.15.1
  '@types/eslint-config-prettier': 6.11.3
  '@types/fs-extra': 11.0.4
  '@types/node': 22.16.4
  '@typescript-eslint/types': 8.37.0
  '@vitest/coverage-v8': 3.2.4
  '@vitest/eslint-plugin': 1.3.4
  ajv: 8.17.1
  ajv-draft-04: 1.0.0
  astro: ^5.6.1
  cac: 6.7.14
  consola: 3.4.2
  eslint: 9.31.0
  eslint-config-flat-gitignore: 2.1.0
  eslint-config-prettier: 10.1.8
  eslint-flat-config-utils: 2.1.0
  eslint-merge-processors: 2.0.0
  eslint-plugin-command: 3.3.1
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-jsdoc: 51.4.1
  eslint-plugin-json-schema-validator: 5.4.1
  eslint-plugin-jsonc: 2.20.1
  eslint-plugin-n: 17.21.0
  eslint-plugin-no-only-tests: 3.3.0
  eslint-plugin-node-dependencies: 1.1.2
  eslint-plugin-perfectionist: 4.15.0
  eslint-plugin-pnpm: 1.0.0
  eslint-plugin-prettier: 5.5.2
  eslint-plugin-regexp: 2.9.0
  eslint-plugin-toml: 0.12.0
  eslint-plugin-unicorn: 59.0.1
  eslint-plugin-unused-imports: 4.1.4
  eslint-plugin-yml: 1.18.0
  eslint-typegen: 2.2.1
  execa: 9.6.0
  fast-glob: 3.3.3
  fs-extra: 11.3.0
  globals: 16.3.0
  husky: 9.1.7
  is-in-ci: 1.0.0
  lint-staged: 16.1.2
  local-pkg: 1.1.1
  memfs: 4.17.2
  package-directory: 8.1.0
  package-manager-detector: 1.3.0
  prettier: 3.6.2
  publint: 0.3.12
  rimraf: 6.0.1
  semantic-release: 24.2.7
  sharp: ^0.34.2
  sort-package-json: 3.4.0
  ts-essentials: 10.1.1
  tsup: 8.5.0
  tsx: 4.20.3
  type-fest: 4.41.0
  typescript: 5.8.3
  typescript-eslint: 8.37.0
  vitest: 3.2.4
overrides:
  jiti: <2.2.0
  read-pkg-up@^11: npm:read-package-up
