packages:
  - .
  - docs
  - packages/*
  - scripts

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  read-pkg-up@^11: npm:read-package-up
  zod: <4.0.0

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: true
