// This file is generated by scripts/generate-types.ts
// Do not edit this file directly.

import type {Linter} from 'eslint'
import type {FlatConfigComposer, ResolvableFlatConfig} from 'eslint-flat-config-utils'
import type {Rules} from './rules'

export type {FlatConfigComposer, ResolvableFlatConfig}

/**
 * Represents a value that resolves to one or more ESLint flat configurations.
 * @see https://jsr.io/@antfu/eslint-flat-config-utils/doc/~/ResolvableFlatConfig
 */
export type AwaitableFlatConfig = ResolvableFlatConfig<Config>

/**
 * Represents the configuration for the linter.
 * This interface extends the {@link Linter.Config} interface, expanding {@link Rules} to include the rules defined in all configurations.
 *
 * @see https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects
 */
export interface Config extends Linter.Config<Linter.RulesRecord & Rules> {}

/**
 * Defines a 'composer' for ESLint flat configurations.
 * @see https://jsr.io/@antfu/eslint-flat-config-utils/doc/~/FlatConfigComposer
 */
export type ConfigComposer = FlatConfigComposer<Config, ConfigNames>

/**
 * Defines the names of the available ESLint configurations.
 */
export type ConfigNames =
  | '@bfra.me/gitignore'
  | '@bfra.me/ignores'
  | '@bfra.me/javascript/options'
  | '@bfra.me/javascript/rules'
  | '@bfra.me/eslint-comments/rules'
  | '@bfra.me/jsdoc'
  | '@bfra.me/imports'
  | '@bfra.me/command'
  | '@bfra.me/prettier'
  | '@bfra.me/perfectionist'
  | '@bfra.me/typescript/plugins'
  | '@bfra.me/typescript/parser'
  | '@bfra.me/typescript/type-aware-parser'
  | '@bfra.me/typescript/rules'
  | '@bfra.me/typescript/type-aware-rules'
  | '@bfra.me/vitest/plugin'
  | '@bfra.me/vitest/rules'
  | '@bfra.me/epilogue/cli'
  | '@bfra.me/epilogue/configs'
  | '@bfra.me/epilogue/scripts'
  | '@bfra.me/epilogue/commonjs'
  | '@bfra.me/epilogue/dts'
  | '@bfra.me/epilogue'
