// Re-export generators
export {
  cleanCodeExample,
  createBadge,
  createCard,
  createCardGrid,
  createDiffSummary,
  createTabs,
  detectLanguage,
  extractAutoSections,
  extractManualSections,
  formatCodeBlock,
  formatCodeExamples,
  formatFunctionExamples,
  formatGroupedExamples,
  formatTypeExamples,
  formatUsageExample,
  generateAPICompact,
  generateAPIReference,
  generateCategoryReference,
  generateFrontmatter,
  generateInstallTabs,
  generateMDXDocument,
  groupExamplesByCategory,
  hasAutoContent,
  hasManualContent,
  mapToStarlightComponents,
  mergeContent,
  parseFrontmatter,
  sanitizeContent,
  sanitizeTextContent,
  stringifyFrontmatter,
  stripSentinelMarkers,
  validateMarkerPairing,
  validateMDXSyntax,
  wrapAutoSection,
  wrapManualSection,
} from './generators'

export type {
  CodeExampleOptions,
  ComponentMapperConfig,
  ContentSection,
  MDXGeneratorOptions,
  MergeOptions,
  MergeResult,
  SectionMapper,
} from './generators'

// Re-export orchestrator
export {
  createPackageScanner,
  createSyncOrchestrator,
  createValidationPipeline,
  filterPackagesByPattern,
  groupPackagesByScope,
  isValidFilePath,
  validateContentString,
  validateDocument,
} from './orchestrator'

export type {
  PackageScannerOptions,
  ScannedPackage,
  ScanResult,
  SyncOrchestrator,
  SyncOrchestratorOptions,
  ValidationError,
  ValidationPipelineOptions,
  ValidationResult,
  ValidationWarning,
} from './orchestrator'

// Re-export parsers
export {
  analyzePublicAPI,
  analyzeTypeScriptContent,
  analyzeTypeScriptFile,
  assertPackageAPI,
  assertPackageInfo,
  assertParseError,
  buildDocSlug,
  createProject,
  extractDocsConfig,
  extractExportedFunctions,
  extractExportedTypes,
  extractJSDocInfo,
  extractPackageAPI,
  extractReExports,
  findEntryPoint,
  findExportedSymbols,
  findReadmePath,
  findSection,
  flattenSections,
  getExportedSymbolInfo,
  getExportsByKind,
  getPackageScope,
  getSectionsByLevel,
  getTableOfContents,
  getUnscopedName,
  hasJSDoc,
  isDocConfigSource,
  isExportedFunction,
  isExportedType,
  isJSDocInfo,
  isJSDocParam,
  isJSDocTag,
  isMDXFrontmatter,
  isPackageAPI,
  isPackageInfo,
  isParseError,
  isReadmeContent,
  isReadmeSection,
  isReExport,
  isSafeContent,
  isSafeFilePath,
  isSymbolExported,
  isSyncError,
  isValidHeadingLevel,
  isValidPackageName,
  isValidSemver,
  parseJSDoc,
  parsePackageComplete,
  parsePackageJson,
  parsePackageJsonContent,
  parseReadme,
  parseReadmeFile,
  parseSourceContent,
  parseSourceFile,
} from './parsers'

export type {
  ExportAnalyzerOptions,
  JSDocableDeclaration,
  PackageInfoOptions,
  PackageJsonSchema,
  PublicAPIAnalysis,
  ReadmeParserOptions,
  ResolvedExport,
  TypeScriptParserOptions,
} from './parsers'

export type {
  CLIOptions,
  DocConfig,
  DocConfigSource,
  ExportedFunction,
  ExportedType,
  FileChangeEvent,
  FunctionParameter,
  InferSchema,
  JSDocInfo,
  JSDocParam,
  JSDocTag,
  MDXDocument,
  MDXFrontmatter,
  PackageAPI,
  PackageInfo,
  ParseError,
  ParseErrorCode,
  ParseResult,
  ReadmeContent,
  ReadmeSection,
  ReExport,
  SyncError,
  SyncErrorCode,
  SyncInfo,
  SyncResult,
  SyncSummary,
} from './types'

export {SENTINEL_MARKERS} from './types'

// Re-export utils
export {
  createHeadingPattern,
  extractCodeBlocks,
  findEmptyMarkdownLinks,
  hasComponent,
  parseJSXAttributes,
  parseJSXTags,
  sanitizeAttribute,
  sanitizeForMDX,
  sanitizeJSXTag,
} from './utils'

// Re-export watcher
export {
  categorizeFile,
  consolidateEvents,
  createDocChangeDetector,
  createDocDebouncer,
  createDocWatcher,
  deduplicateEvents,
  determineRegenerationScope,
  filterDocumentationChanges,
  groupChangesByPackage,
  hasAnyFileChanged,
} from './watcher'

export type {
  BatchChangeHandler,
  DocChangeDetector,
  DocChangeDetectorOptions,
  DocChangeHandler,
  DocDebouncer,
  DocDebouncerOptions,
  DocFileWatcher,
  DocWatcherOptions,
  FileCategory,
  PackageChangeAnalysis,
  RegenerationScope,
} from './watcher'
