---
name: Prepare Job
description: Prepare the job by installing required tools and dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@ac5bf11548bf5e19b8aadb8182072616590fa4a6
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: '.node-version'

    - name: Install dependencies and build packages
      uses: ./.github/actions/pnpm-install
