name: Prepare Job
description: Prepare the job by installing required tools and dependencies

runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: 'bash -Eeuo pipefail {0}'

    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: '.node-version'

    - id: cache-node-modules
      name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - if: steps.cache-node-modules.outputs.cache-hit != 'true' || steps.setup-node.outputs.cache-hit != true
      env:
        HUSKY: '0'
      name: Install dependencies and build packages
      run: pnpm run bootstrap
      shell: 'bash -Eeuo pipefail {0}'
