# Continuous Integration jobs for this repository.
---
name: CI

'on':
  push:
    branches: [main, "renovate/**"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
        env:
          NODE_VERSION: 18.15.0 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
