---
# Renovate this repository if this workflow file or the Renovate configuration file is changed.
name: Renovate

'on':
  pull_request:
    paths:
      - '.github/workflows/renovate.yaml'
      - '.github/renovate.json'
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    paths:
      - '.github/workflows/renovate.yaml'
      - '.github/renovate.json'
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

permissions: {}

jobs:
  Renovate:
    uses: bfra-me/renovate-config/.github/workflows/renovate.yaml@cd72bb2a00ec105126ddf03f16f69e1380e0e0ea # v1.15.0
    with:
      autodiscover: false
      dry_run: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
      print_config: ${{ inputs.print_config || false }}
    secrets: inherit
